kosaraju: kosaraju.o kosaraheader.o 
		 g++ kosaraju.o kosaraheader.o -o kosaraju.bin

kosaraju.o: kosaraju.cpp
			g++ -c kosaraju.cpp

kosaraheader.o: kosaraheader.cpp
				g++ -c kosaraheader.cpp

clean:
		rm *.o kosaraju
